# Generated by Django 5.1.6 on 2025-03-06 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MentalHealthResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=100, unique=True)),
                ('question_title', models.TextField()),
                ('question_text', models.TextField()),
                ('topic', models.CharField(max_length=255)),
                ('therapist_info', models.TextField()),
                ('answer_text', models.TextField()),
                ('upvotes', models.IntegerField()),
            ],
        ),
    ]
